colors.draw_bold_text_with_bright_colors = true

# Cyberpunk-Neon colours
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = '0x000b1e'
foreground = '0x0abdc6'

[colors.dim]
black = '0x1c61c2'
red = '0xff0000'
green = '0xd300c4'
yellow = '0xf57800'
blue = '0x123e7c'
magenta = '0x711c91'
cyan = '0x0abdc6'
white = '0xd7d7d5'

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "JetBrainsMonoNerdFontMono"

[window]
option_as_alt = "Both"
opacity = 0.9

#[env]
#TERM = "xterm-256color"

# Uncomment for Windows
#[shell]
#program = "wsl.exe"
#args = ["--cd","~"]
[terminal.shell]
program = "tmux"
args = []


